(defun bench (fn n)
   (terpri)
   (setq tbase base)
   (setq base 10.)
   (terpri)
   (princ "Benchmarking ")(princ fn)(princ " with input: ")(princ n)
   (terpri)
   (setq t0 (time))
   (setq r1 (car (mapcar fn (list n))))
   (setq t1 (time))
   (terpri)
   (princ "      Result: ")(princ r1)(terpri)
   (princ "Time elapsed: ")(princ (-$ t1 t0))(princ " seconds")
   (terpri)
   (setq base tbase)
   (list r1 (-$ t1 t0))
)

